#ifndef _retcodes_h
#define _retcodes_h

typedef enum
{
	OK=0,

	// return codes for STORAGE MODULE (STORM)
	STORM_FILENOTFOUND,
	STORM_FILEEXISTS,
	STORM_FILEDOESNOTEXIST,
	STORM_FILEALREADYOPENED,
	STORM_FILEALREADYCLOSED,
	STORM_EOF,
	STORM_FILEFULL,
	STORM_FILEOPENERROR,
	STORM_FILECLOSEERROR,
	STORM_FILENOTOPENED,
	STORM_OPENEDFILELIMITREACHED,
	STORM_INVALIDPAGE,
	STORM_INVALIDFILEHANDLE,
	STORM_CANNOTCREATEFILE,
	STORM_CANNOTDESTROYFILE,
	STORM_PAGENOTINBUFFER,
	STORM_PAGEISPINNED,
	STORM_ALLPAGESPINNED,
	STORM_IOERROR,
	STORM_MEMALLOCERROR,

	// return codes for RECORD MODULE (REM)


	REM_INVALIDRECORDSIZE,
	REM_INVALIDRECORDID,
	REM_PAGESCANOUTOFBOUNDS,
	REM_RECORDNOTFOUND,







	// return codes for INDEX MODULE (INXM)





	// return codes for SYSTEM MODULE (SYSM)
	SYSM_CANNOTCREATEDATABASE,
	SYSM_CANNOTACCESSDATABASE,
	SYSM_CANNOTDELETEDATABASE,
	SYSM_DATABASEALREADYOPENED,
	SYSM_DATABASECLOSED,
	SYSM_METADATANAME,
	SYSM_TABLEALREADYEXISTS,
	SYSM_TABLEDOESNOTEXIST,
	SYSM_NOATTRIBUTEFOUND,
	SYSM_ATTRIBUTEALREADYINDEXED,
	SYSM_ATTRIBUTENOTINDEXED,




	// return codes for SirenSQL MODULE (SSQLM)
	SSQLM_INVALIDCOMMAND,
	SSQLM_INVALIDTABLENAME,
	SSQLM_INVALIDARGUMENTNAME,
	SSQLM_STRINGTOOLONG,
	SSQLM_MAXATTRIBUTES,
	SSQLM_NOENTRYTOINDEX,
	SSQLM_NOVALUESTOINSERT,




	// return code for USER INTERFACE MODULE (UIM)

	UIM_WRONGCOMMAND,
	UIM_NODATABASEOPEN,
	UIM_WRONGDATABASENAME,
	UIM_ATTRIBUTENOTINDEXED,
	UIM_TOOMUCHTABLES





} t_rc;


void DisplayReturnCode(t_rc rc);
void DisplayMessage(char *msg);

#endif
